services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    # Bind-mount your source so code edits reload immediately
    volumes:
      - ./:/app
    # If you want live reload from Django's runserver, leave default CMD.
    # For gunicorn (if installed), you could override:
    # command: gunicorn etickets.wsgi:application --bind 0.0.0.0:8000 --workers 2 --timeout 120
