app = "etickets-v10"
primary_region = "cdg"

[build]

[deploy]
  release_command = "sh -c 'python manage.py migrate && python manage.py collectstatic --noinput'"
[env]
  DJANGO_SETTINGS_MODULE = "etickets.settings"
  PYTHONUNBUFFERED = "1"
  PORT = "8000"
  SERVE_MEDIA = "1"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[processes]
  app = "gunicorn etickets.wsgi:application --bind 0.0.0.0:8000"

[[mounts]]
  source = "media_data"
  destination = "/app/media"

# (optionnel, utile si tu fais collectstatic)
[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static/"

