@"
name: CI
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # si "coverage" n'est pas dans requirements.txt :
          # pip install coverage
      - name: Migrations check
        run: |
          python manage.py makemigrations --check --dry-run
          python manage.py migrate --noinput
      - name: Tests + Coverage (>= 80%)
        run: |
          coverage run manage.py test
          coverage report -m --fail-under=80
          coverage html
      - name: Upload coverage HTML
        uses: actions/upload-artifact@v4
        with:
          name: htmlcov
          path: htmlcov/
"@ | Set-Content .github/workflows/ci.yml -Encoding UTF8
